<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Nexus.Hardware.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Nexus.Hardware\Nexus.Hardware.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.6" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.5" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.5" />
    <PackageReference Include="System.Management" Version="10.0.5" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
  </ItemGroup>
</Project>
