namespace Nexus.Core.Models;

/// <summary>
/// Represents a single step within a tool execution plan generated by <see cref="Nexus.Core.Abstractions.IToolPlanner"/>.
/// </summary>
/// <param name="StepNumber">1-based ordinal position of this step within the plan.</param>
/// <param name="Description">Natural-language description of what this step should accomplish.</param>
/// <param name="MatchedToolName">
/// Name of the tool matched to this step, or <see langword="null"/> when no tool met the similarity threshold.
/// Steps with a null <see cref="MatchedToolName"/> are skipped during execution but retained for observability.
/// </param>
/// <param name="Similarity">
/// Cosine similarity score (0–1) used to match this step to a tool.
/// Set to 1.0 when the substring fallback path was used instead of embedding similarity.
/// </param>
public sealed record ToolPlanStep(
    int StepNumber,
    string Description,
    string? MatchedToolName,
    float Similarity);

/// <summary>
/// An ordered plan produced by <see cref="Nexus.Core.Abstractions.IToolPlanner"/> describing
/// which tools to call and in what sequence to fulfil a user request.
/// </summary>
/// <remarks>
/// Entries in <see cref="Steps"/> with <see cref="ToolPlanStep.MatchedToolName"/> == <see langword="null"/>
/// are skipped by <see cref="Nexus.Core.Services.AgentService"/>'s plan executor but are preserved in
/// the returned plan for observability and debug logging. The overall plan is still returned non-null
/// from <see cref="Nexus.Core.Abstractions.IToolPlanner.GeneratePlanAsync"/> even when every step is
/// unmatched — fall-through to the normal tool loop is the executor's responsibility when no step
/// yields a usable tool call.
/// </remarks>
/// <param name="Steps">Ordered list of plan steps (at most 5). May be empty if no steps were matched.</param>
/// <param name="RawPlanText">The unprocessed LLM output from which <see cref="Steps"/> were parsed.</param>
public sealed record ToolPlan(
    IReadOnlyList<ToolPlanStep> Steps,
    string RawPlanText);
