<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Nexus.Models\Nexus.Models.csproj" />
    <ProjectReference Include="..\Nexus.ModelRegistry\Nexus.ModelRegistry.csproj" />
  </ItemGroup>
</Project>
